declare module '@kangc/v-md-editor'
declare module '@kangc/v-md-editor/lib/theme/vuepress'
declare module '@kangc/v-md-editor/lib/theme/github'
declare module '@kangc/v-md-editor/lib/style/base-editor.css'
declare module '@kangc/v-md-editor/lib/theme/style/vuepress.css'
declare module '@kangc/v-md-editor/lib/theme/style/github.css'